/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mars.rover.kotlin.app

object Mars {
    var position = Coordinate(0,0)
    var direction = "South"
    fun forward(){
        position.x += 1
    }
    fun backward(){}
    fun left(){
        if (direction == "South"){
            direction = "East"
        } else if (direction == "East"){
            direction = "North"
        } else if (direction == "North"){
            direction = "West"
        } else direction = "South"
    }
    fun right(){
        if (direction == "South"){
            direction = "West"
        } else if (direction == "West"){
            direction = "North"
        } else if (direction == "North"){
            direction = "East"
        } else direction = "South"
    }
}

fun main(){
    Mars.left()
    println(Mars.direction)
    Mars.right()
    println(Mars.direction)
}

class Coordinate(x: Int, y: Int) {
    var x = x
    var y = y
   override fun toString(): String{
       return "${x}, ${y}"
    }
}